name: API spec

on: [push, pull_request]

permissions:
  contents: read

jobs:
  api-spec:
    name: API spec tests

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:11.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Python
        uses: actions/setup-python@7f80679172b057fc5e90d70d197929d454754a5a # v2.3.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: "1.1.12"
          virtualenvs-in-project: true

      - name: Set up cache
        uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-py-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run newman and test service
        env:
          SECRET_KEY: secret_key
          DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
        run: |
          poetry run alembic upgrade head
          poetry run uvicorn app.main:app &
          APIURL=http://localhost:8000/api ./postman/run-api-tests.sh
          poetry run alembic downgrade base
