name: Deploy

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: nsidnev/fastapi-realworld-example-app
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: Build Container

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: Build image and publish to registry
        run: |
          docker build -t $IMAGE_NAME:latest .
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:latest
